

# This file was *autogenerated* from the file sage_files/sage_19.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_512 = Integer(512); _sage_const_68719031793 = Integer(68719031793); _sage_const_68719476736 = Integer(68719476736); _sage_const_2 = Integer(2); _sage_const_262143 = Integer(262143); _sage_const_262144 = Integer(262144); _sage_const_256 = Integer(256)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_1 /_sage_const_512 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_68719031793 /_sage_const_68719476736 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_68719031793 /_sage_const_68719476736 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_262143 /_sage_const_262144  + skoX + ((lambda_var_0)**_sage_const_2 ) + (_sage_const_1 /_sage_const_256  * lambda_var_0))), (delta >= (_sage_const_262143 /_sage_const_262144  + (-_sage_const_1  * skoX) + (-_sage_const_1  * ((lambda_var_0)**_sage_const_2 )) + (-_sage_const_1 /_sage_const_256  * lambda_var_0))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


