

# This file was *autogenerated* from the file sage_files/sage_20.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_741455 = Integer(741455); _sage_const_524288 = Integer(524288); _sage_const_1 = Integer(1); _sage_const_1048575 = Integer(1048575); _sage_const_1048576 = Integer(1048576); _sage_const_2 = Integer(2); _sage_const_274877906944 = Integer(274877906944)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_741455 /_sage_const_524288 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_1048575 /_sage_const_1048576 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_1048575 /_sage_const_1048576 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_274877906944  * (((_sage_const_741455  + (_sage_const_524288  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_274877906944  * (((_sage_const_741455  + (_sage_const_524288  * lambda_var_0)))**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


