

# This file was *autogenerated* from the file sage_files/sage_1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_9 = Integer(9); _sage_const_20 = Integer(20); _sage_const_47 = Integer(47); _sage_const_64 = Integer(64); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
var('delta')
var('skoS')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_9 /_sage_const_20 ), (delta >= (-_sage_const_47 /_sage_const_64  + lambda_var_0 + ((lambda_var_0)**_sage_const_2 ))), (delta >= (_sage_const_47 /_sage_const_64  + (-_sage_const_1  * lambda_var_0) + (-_sage_const_1  * ((lambda_var_0)**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


