

# This file was *autogenerated* from the file sage_files/sage_0.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_15 = Integer(15); _sage_const_10 = Integer(10); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_160 = Integer(160); _sage_const_20 = Integer(20)
var('delta')
var('skoX')
var('skoS2')
var('pi')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (skoX > _sage_const_0 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (skoX < _sage_const_1 ), ((_sage_const_1 /_sage_const_8  * skoX * (_sage_const_15  + (-_sage_const_8  * lambda_var_0))) > _sage_const_0 ), ((-_sage_const_1 /_sage_const_10  + (_sage_const_3  * pi) + (_sage_const_6  * pi * skoS2)) > (-_sage_const_1 /_sage_const_160  * (_sage_const_1  + (_sage_const_8  * lambda_var_0)) * (_sage_const_1  + (_sage_const_10  * pi) + (_sage_const_20  * pi * skoS2)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


