

# This file was *autogenerated* from the file gus_sage_files/sage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
var('delta')
var('skoSINS')
var('skoM')
var('skoCOSS')
var('skoS')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoM >= _sage_const_2 ), (skoS >= _sage_const_2 ), (delta >= (-_sage_const_1  + ((skoCOSS)**_sage_const_2 ) + ((skoSINS)**_sage_const_2 ))), (delta >= (_sage_const_1  + (-_sage_const_1  * ((skoCOSS)**_sage_const_2 )) + (-_sage_const_1  * ((skoSINS)**_sage_const_2 )))))
E = qf.exists(['skoCOSS', 'skoS'],F)
print(qepcad(E, memcells='1000000000 +L5000'))


