

# This file was *autogenerated* from the file gus_sage_files/sage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_217 = Integer(217); _sage_const_100 = Integer(100); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
var('delta')
var('skoS')
var('skoCOSS')
var('skoSINS')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_217 /_sage_const_100 ),  qf.or_((delta < (-_sage_const_1  + ((skoCOSS)**_sage_const_2 ) + ((skoSINS)**_sage_const_2 ))), (delta < (_sage_const_1  + (-_sage_const_1  * ((skoCOSS)**_sage_const_2 )) + (-_sage_const_1  * ((skoSINS)**_sage_const_2 ))))))
E = qf.exists(['skoSINS', 'skoCOSS'],F)
print(qepcad(E, memcells='1000000000 +L5000'))


