

# This file was *autogenerated* from the file sage_files/sage_14.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_81 = Integer(81); _sage_const_64 = Integer(64); _sage_const_1 = Integer(1); _sage_const_583 = Integer(583); _sage_const_1024 = Integer(1024); _sage_const_2 = Integer(2); _sage_const_379 = Integer(379); _sage_const_4096 = Integer(4096)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_81 /_sage_const_64 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_583 /_sage_const_1024 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_583 /_sage_const_1024 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), ((_sage_const_1 /_sage_const_64  * skoX * (_sage_const_379  + (_sage_const_64  * lambda_var_0))) > _sage_const_0 ), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_4096  * (((_sage_const_81  + (_sage_const_64  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_4096  * (((_sage_const_81  + (_sage_const_64  * lambda_var_0)))**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


