

# This file was *autogenerated* from the file sage_files/sage_17.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_161 = Integer(161); _sage_const_256 = Integer(256); _sage_const_1 = Integer(1); _sage_const_159057 = Integer(159057); _sage_const_262144 = Integer(262144); _sage_const_2 = Integer(2); _sage_const_512 = Integer(512); _sage_const_3019 = Integer(3019); _sage_const_65536 = Integer(65536)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_161 /_sage_const_256 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_159057 /_sage_const_262144 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_159057 /_sage_const_262144 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), ((_sage_const_1 /_sage_const_512  * skoX * (_sage_const_3019  + (_sage_const_512  * lambda_var_0))) > _sage_const_0 ), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_65536  * (((_sage_const_161  + (_sage_const_256  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_65536  * (((_sage_const_161  + (_sage_const_256  * lambda_var_0)))**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


