

# This file was *autogenerated* from the file sage_files/sage_0.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_40 = Integer(40); _sage_const_10 = Integer(10); _sage_const_20 = Integer(20)
var('delta')
var('skoX')
var('skoS2')
var('pi')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= skoX), (lambda_var_0 >= -_sage_const_1 /_sage_const_2 ), (skoS2 >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (skoX > _sage_const_0 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (skoX < _sage_const_1 ), (delta >= (-_sage_const_1  * skoX)), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_3 /_sage_const_4  + lambda_var_0 + ((lambda_var_0)**_sage_const_2 ) + (-_sage_const_1  * skoX))), (delta >= (_sage_const_3 /_sage_const_4  + skoX + (-_sage_const_1  * lambda_var_0) + (-_sage_const_1  * ((lambda_var_0)**_sage_const_2 )))), ((-_sage_const_1 /_sage_const_4  + (_sage_const_1 /_sage_const_2  * pi) + (pi * skoS2)) >= (_sage_const_1 /_sage_const_40  * (_sage_const_1  + (_sage_const_2  * lambda_var_0)) * (_sage_const_1  + (_sage_const_10  * pi) + (_sage_const_20  * pi * skoS2)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


