

# This file was *autogenerated* from the file sage_files/sage_4.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4096 = Integer(4096); _sage_const_97 = Integer(97); _sage_const_128 = Integer(128); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_445521 = Integer(445521); _sage_const_262144 = Integer(262144); _sage_const_9409 = Integer(9409); _sage_const_16384 = Integer(16384); _sage_const_64 = Integer(64); _sage_const_4 = Integer(4); _sage_const_8388608 = Integer(8388608); _sage_const_20481 = Integer(20481); _sage_const_12291 = Integer(12291); _sage_const_12288 = Integer(12288); _sage_const_4097 = Integer(4097)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 >= -_sage_const_1 /_sage_const_4096 ), (skoS >= _sage_const_97 /_sage_const_128 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((_sage_const_445521 /_sage_const_262144  + (-_sage_const_9409 /_sage_const_16384  * skoS) + (_sage_const_97 /_sage_const_64  * lambda_var_0) + (-_sage_const_97 /_sage_const_128  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))) >= (-_sage_const_2  + (_sage_const_1 /_sage_const_8388608  * skoS * (((_sage_const_1  + (_sage_const_4096  * lambda_var_0)) * (_sage_const_20481  + (_sage_const_4096  * lambda_var_0))) + (_sage_const_4096  * skoS * (_sage_const_12291  + (_sage_const_4096  * skoS) + (_sage_const_12288  * lambda_var_0))))) + (_sage_const_1 /_sage_const_8388608  * (_sage_const_1  + (_sage_const_4096  * lambda_var_0)) * (_sage_const_4097  + (_sage_const_4096  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


