

# This file was *autogenerated* from the file sage_files/sage_18.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_536870912 = Integer(536870912); _sage_const_12776809 = Integer(12776809); _sage_const_16777216 = Integer(16777216); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_7677296091636825 = Integer(7677296091636825); _sage_const_4503599627370496 = Integer(4503599627370496); _sage_const_163246848222481 = Integer(163246848222481); _sage_const_281474976710656 = Integer(281474976710656); _sage_const_8388608 = Integer(8388608); _sage_const_4 = Integer(4); _sage_const_144115188075855872 = Integer(144115188075855872); _sage_const_2684354561 = Integer(2684354561); _sage_const_1610612739 = Integer(1610612739); _sage_const_1610612736 = Integer(1610612736); _sage_const_536870913 = Integer(536870913)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 >= -_sage_const_1 /_sage_const_536870912 ), (skoS >= _sage_const_12776809 /_sage_const_16777216 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((_sage_const_7677296091636825 /_sage_const_4503599627370496  + (-_sage_const_163246848222481 /_sage_const_281474976710656  * skoS) + (_sage_const_12776809 /_sage_const_8388608  * lambda_var_0) + (-_sage_const_12776809 /_sage_const_16777216  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))) >= (-_sage_const_2  + (_sage_const_1 /_sage_const_144115188075855872  * skoS * (((_sage_const_1  + (_sage_const_536870912  * lambda_var_0)) * (_sage_const_2684354561  + (_sage_const_536870912  * lambda_var_0))) + (_sage_const_536870912  * skoS * (_sage_const_1610612739  + (_sage_const_536870912  * skoS) + (_sage_const_1610612736  * lambda_var_0))))) + (_sage_const_1 /_sage_const_144115188075855872  * (_sage_const_1  + (_sage_const_536870912  * lambda_var_0)) * (_sage_const_536870913  + (_sage_const_536870912  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


