

# This file was *autogenerated* from the file sage_files/sage_7.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_1559 = Integer(1559); _sage_const_2048 = Integer(2048); _sage_const_1073709055 = Integer(1073709055); _sage_const_536870912 = Integer(536870912); _sage_const_163841 = Integer(163841); _sage_const_32768 = Integer(32768); _sage_const_98307 = Integer(98307); _sage_const_33554432 = Integer(33554432); _sage_const_49153 = Integer(49153); _sage_const_8 = Integer(8); _sage_const_16384 = Integer(16384); _sage_const_4 = Integer(4)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((lambda_var_0 + (-_sage_const_1  * skoS)) <= -_sage_const_1559 /_sage_const_2048 ), ((-_sage_const_1073709055 /_sage_const_536870912  + (_sage_const_1 /_sage_const_536870912  * skoS * (_sage_const_163841  + (_sage_const_32768  * skoS * (_sage_const_98307  + (_sage_const_32768  * skoS)))))) <= (-_sage_const_1 /_sage_const_33554432  * (_sage_const_1559  + (_sage_const_2048  * lambda_var_0)) * (-_sage_const_49153  + (_sage_const_8  * (_sage_const_1  + skoS) * (_sage_const_1559  + (_sage_const_2048  * lambda_var_0))) + (_sage_const_16384  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


