

# This file was *autogenerated* from the file sage_files/sage_6.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_32768 = Integer(32768); _sage_const_1559 = Integer(1559); _sage_const_2048 = Integer(2048); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_57185679 = Integer(57185679); _sage_const_33554432 = Integer(33554432); _sage_const_2430481 = Integer(2430481); _sage_const_4194304 = Integer(4194304); _sage_const_1024 = Integer(1024); _sage_const_4 = Integer(4); _sage_const_536870912 = Integer(536870912); _sage_const_163841 = Integer(163841); _sage_const_98307 = Integer(98307); _sage_const_98304 = Integer(98304); _sage_const_32769 = Integer(32769)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 >= -_sage_const_1 /_sage_const_32768 ), (skoS >= _sage_const_1559 /_sage_const_2048 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((_sage_const_57185679 /_sage_const_33554432  + (-_sage_const_2430481 /_sage_const_4194304  * skoS) + (_sage_const_1559 /_sage_const_1024  * lambda_var_0) + (-_sage_const_1559 /_sage_const_2048  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))) >= (-_sage_const_2  + (_sage_const_1 /_sage_const_536870912  * skoS * (((_sage_const_1  + (_sage_const_32768  * lambda_var_0)) * (_sage_const_163841  + (_sage_const_32768  * lambda_var_0))) + (_sage_const_32768  * skoS * (_sage_const_98307  + (_sage_const_32768  * skoS) + (_sage_const_98304  * lambda_var_0))))) + (_sage_const_1 /_sage_const_536870912  * (_sage_const_1  + (_sage_const_32768  * lambda_var_0)) * (_sage_const_32769  + (_sage_const_32768  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


