

# This file was *autogenerated* from the file sage_files/sage_17.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_399275 = Integer(399275); _sage_const_524288 = Integer(524288); _sage_const_18014398375264255 = Integer(18014398375264255); _sage_const_9007199254740992 = Integer(9007199254740992); _sage_const_671088641 = Integer(671088641); _sage_const_134217728 = Integer(134217728); _sage_const_402653187 = Integer(402653187); _sage_const_35184372088832 = Integer(35184372088832); _sage_const_201326593 = Integer(201326593); _sage_const_128 = Integer(128); _sage_const_67108864 = Integer(67108864); _sage_const_4 = Integer(4)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((lambda_var_0 + (-_sage_const_1  * skoS)) <= -_sage_const_399275 /_sage_const_524288 ), ((-_sage_const_18014398375264255 /_sage_const_9007199254740992  + (_sage_const_1 /_sage_const_9007199254740992  * skoS * (_sage_const_671088641  + (_sage_const_134217728  * skoS * (_sage_const_402653187  + (_sage_const_134217728  * skoS)))))) <= (-_sage_const_1 /_sage_const_35184372088832  * (_sage_const_399275  + (_sage_const_524288  * lambda_var_0)) * (-_sage_const_201326593  + (_sage_const_128  * (_sage_const_1  + skoS) * (_sage_const_399275  + (_sage_const_524288  * lambda_var_0))) + (_sage_const_67108864  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


