

# This file was *autogenerated* from the file sage_files/sage_0.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_32 = Integer(32); _sage_const_41 = Integer(41); _sage_const_27 = Integer(27); _sage_const_24 = Integer(24); _sage_const_9 = Integer(9)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 >= -_sage_const_1 /_sage_const_8 ), (skoS >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((-_sage_const_2  + (_sage_const_1 /_sage_const_32  * skoS * (((_sage_const_1  + (_sage_const_8  * lambda_var_0)) * (_sage_const_41  + (_sage_const_8  * lambda_var_0))) + (_sage_const_8  * skoS * (_sage_const_27  + (_sage_const_8  * skoS) + (_sage_const_24  * lambda_var_0))))) + (_sage_const_1 /_sage_const_32  * (_sage_const_1  + (_sage_const_8  * lambda_var_0)) * (_sage_const_9  + (_sage_const_8  * lambda_var_0)))) <= _sage_const_0 ))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


