

# This file was *autogenerated* from the file sage_files/sage_3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_16 = Integer(16); _sage_const_1047551 = Integer(1047551); _sage_const_524288 = Integer(524288); _sage_const_5121 = Integer(5121); _sage_const_1024 = Integer(1024); _sage_const_3075 = Integer(3075); _sage_const_8192 = Integer(8192); _sage_const_1537 = Integer(1537); _sage_const_32 = Integer(32); _sage_const_512 = Integer(512); _sage_const_4 = Integer(4)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((lambda_var_0 + (-_sage_const_1  * skoS)) <= -_sage_const_11 /_sage_const_16 ), ((-_sage_const_1047551 /_sage_const_524288  + (_sage_const_1 /_sage_const_524288  * skoS * (_sage_const_5121  + (_sage_const_1024  * skoS * (_sage_const_3075  + (_sage_const_1024  * skoS)))))) <= (-_sage_const_1 /_sage_const_8192  * (_sage_const_11  + (_sage_const_16  * lambda_var_0)) * (-_sage_const_1537  + (_sage_const_32  * (_sage_const_1  + skoS) * (_sage_const_11  + (_sage_const_16  * lambda_var_0))) + (_sage_const_512  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


