

# This file was *autogenerated* from the file sage_files/sage_8.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_131072 = Integer(131072); _sage_const_3119 = Integer(3119); _sage_const_4096 = Integer(4096); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_457572895 = Integer(457572895); _sage_const_268435456 = Integer(268435456); _sage_const_9728161 = Integer(9728161); _sage_const_16777216 = Integer(16777216); _sage_const_2048 = Integer(2048); _sage_const_4 = Integer(4); _sage_const_8589934592 = Integer(8589934592); _sage_const_655361 = Integer(655361); _sage_const_393219 = Integer(393219); _sage_const_393216 = Integer(393216); _sage_const_131073 = Integer(131073)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 >= -_sage_const_1 /_sage_const_131072 ), (skoS >= _sage_const_3119 /_sage_const_4096 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((_sage_const_457572895 /_sage_const_268435456  + (-_sage_const_9728161 /_sage_const_16777216  * skoS) + (_sage_const_3119 /_sage_const_2048  * lambda_var_0) + (-_sage_const_3119 /_sage_const_4096  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))) >= (-_sage_const_2  + (_sage_const_1 /_sage_const_8589934592  * skoS * (((_sage_const_1  + (_sage_const_131072  * lambda_var_0)) * (_sage_const_655361  + (_sage_const_131072  * lambda_var_0))) + (_sage_const_131072  * skoS * (_sage_const_393219  + (_sage_const_131072  * skoS) + (_sage_const_393216  * lambda_var_0))))) + (_sage_const_1 /_sage_const_8589934592  * (_sage_const_1  + (_sage_const_131072  * lambda_var_0)) * (_sage_const_131073  + (_sage_const_131072  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


