

# This file was *autogenerated* from the file sage_files/sage_20.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2147483648 = Integer(2147483648); _sage_const_51107237 = Integer(51107237); _sage_const_67108864 = Integer(67108864); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_122836738898661397 = Integer(122836738898661397); _sage_const_72057594037927936 = Integer(72057594037927936); _sage_const_2611949673774169 = Integer(2611949673774169); _sage_const_4503599627370496 = Integer(4503599627370496); _sage_const_33554432 = Integer(33554432); _sage_const_4 = Integer(4); _sage_const_2305843009213693952 = Integer(2305843009213693952); _sage_const_10737418241 = Integer(10737418241); _sage_const_6442450947 = Integer(6442450947); _sage_const_6442450944 = Integer(6442450944); _sage_const_2147483649 = Integer(2147483649)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 >= -_sage_const_1 /_sage_const_2147483648 ), (skoS >= _sage_const_51107237 /_sage_const_67108864 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((_sage_const_122836738898661397 /_sage_const_72057594037927936  + (-_sage_const_2611949673774169 /_sage_const_4503599627370496  * skoS) + (_sage_const_51107237 /_sage_const_33554432  * lambda_var_0) + (-_sage_const_51107237 /_sage_const_67108864  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))) >= (-_sage_const_2  + (_sage_const_1 /_sage_const_2305843009213693952  * skoS * (((_sage_const_1  + (_sage_const_2147483648  * lambda_var_0)) * (_sage_const_10737418241  + (_sage_const_2147483648  * lambda_var_0))) + (_sage_const_2147483648  * skoS * (_sage_const_6442450947  + (_sage_const_2147483648  * skoS) + (_sage_const_6442450944  * lambda_var_0))))) + (_sage_const_1 /_sage_const_2305843009213693952  * (_sage_const_1  + (_sage_const_2147483648  * lambda_var_0)) * (_sage_const_2147483649  + (_sage_const_2147483648  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


