

# This file was *autogenerated* from the file sage_files/sage_2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_1024 = Integer(1024); _sage_const_11 = Integer(11); _sage_const_16 = Integer(16); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_13035 = Integer(13035); _sage_const_8192 = Integer(8192); _sage_const_121 = Integer(121); _sage_const_256 = Integer(256); _sage_const_8 = Integer(8); _sage_const_4 = Integer(4); _sage_const_524288 = Integer(524288); _sage_const_5121 = Integer(5121); _sage_const_3075 = Integer(3075); _sage_const_3072 = Integer(3072); _sage_const_1025 = Integer(1025)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 >= -_sage_const_1 /_sage_const_1024 ), (skoS >= _sage_const_11 /_sage_const_16 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((_sage_const_13035 /_sage_const_8192  + (-_sage_const_121 /_sage_const_256  * skoS) + (_sage_const_11 /_sage_const_8  * lambda_var_0) + (-_sage_const_11 /_sage_const_16  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))) >= (-_sage_const_2  + (_sage_const_1 /_sage_const_524288  * skoS * (((_sage_const_1  + (_sage_const_1024  * lambda_var_0)) * (_sage_const_5121  + (_sage_const_1024  * lambda_var_0))) + (_sage_const_1024  * skoS * (_sage_const_3075  + (_sage_const_1024  * skoS) + (_sage_const_3072  * lambda_var_0))))) + (_sage_const_1 /_sage_const_524288  * (_sage_const_1  + (_sage_const_1024  * lambda_var_0)) * (_sage_const_1025  + (_sage_const_1024  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


