

# This file was *autogenerated* from the file sage_files/sage_10.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_262144 = Integer(262144); _sage_const_12477 = Integer(12477); _sage_const_16384 = Integer(16384); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_3660764277 = Integer(3660764277); _sage_const_2147483648 = Integer(2147483648); _sage_const_155675529 = Integer(155675529); _sage_const_268435456 = Integer(268435456); _sage_const_8192 = Integer(8192); _sage_const_4 = Integer(4); _sage_const_34359738368 = Integer(34359738368); _sage_const_1310721 = Integer(1310721); _sage_const_786435 = Integer(786435); _sage_const_786432 = Integer(786432); _sage_const_262145 = Integer(262145)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 >= -_sage_const_1 /_sage_const_262144 ), (skoS >= _sage_const_12477 /_sage_const_16384 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((_sage_const_3660764277 /_sage_const_2147483648  + (-_sage_const_155675529 /_sage_const_268435456  * skoS) + (_sage_const_12477 /_sage_const_8192  * lambda_var_0) + (-_sage_const_12477 /_sage_const_16384  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))) >= (-_sage_const_2  + (_sage_const_1 /_sage_const_34359738368  * skoS * (((_sage_const_1  + (_sage_const_262144  * lambda_var_0)) * (_sage_const_1310721  + (_sage_const_262144  * lambda_var_0))) + (_sage_const_262144  * skoS * (_sage_const_786435  + (_sage_const_262144  * skoS) + (_sage_const_786432  * lambda_var_0))))) + (_sage_const_1 /_sage_const_34359738368  * (_sage_const_1  + (_sage_const_262144  * lambda_var_0)) * (_sage_const_262145  + (_sage_const_262144  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


