

# This file was *autogenerated* from the file sage_files/sage_16.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_134217728 = Integer(134217728); _sage_const_399275 = Integer(399275); _sage_const_524288 = Integer(524288); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_59978848140075 = Integer(59978848140075); _sage_const_35184372088832 = Integer(35184372088832); _sage_const_159420525625 = Integer(159420525625); _sage_const_274877906944 = Integer(274877906944); _sage_const_262144 = Integer(262144); _sage_const_4 = Integer(4); _sage_const_9007199254740992 = Integer(9007199254740992); _sage_const_671088641 = Integer(671088641); _sage_const_402653187 = Integer(402653187); _sage_const_402653184 = Integer(402653184); _sage_const_134217729 = Integer(134217729)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 >= -_sage_const_1 /_sage_const_134217728 ), (skoS >= _sage_const_399275 /_sage_const_524288 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((_sage_const_59978848140075 /_sage_const_35184372088832  + (-_sage_const_159420525625 /_sage_const_274877906944  * skoS) + (_sage_const_399275 /_sage_const_262144  * lambda_var_0) + (-_sage_const_399275 /_sage_const_524288  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))) >= (-_sage_const_2  + (_sage_const_1 /_sage_const_9007199254740992  * skoS * (((_sage_const_1  + (_sage_const_134217728  * lambda_var_0)) * (_sage_const_671088641  + (_sage_const_134217728  * lambda_var_0))) + (_sage_const_134217728  * skoS * (_sage_const_402653187  + (_sage_const_134217728  * skoS) + (_sage_const_402653184  * lambda_var_0))))) + (_sage_const_1 /_sage_const_9007199254740992  * (_sage_const_1  + (_sage_const_134217728  * lambda_var_0)) * (_sage_const_134217729  + (_sage_const_134217728  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


