

# This file was *autogenerated* from the file sage_files/sage_15.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_199637 = Integer(199637); _sage_const_262144 = Integer(262144); _sage_const_17592181850111 = Integer(17592181850111); _sage_const_8796093022208 = Integer(8796093022208); _sage_const_20971521 = Integer(20971521); _sage_const_4194304 = Integer(4194304); _sage_const_12582915 = Integer(12582915); _sage_const_549755813888 = Integer(549755813888); _sage_const_6291457 = Integer(6291457); _sage_const_8 = Integer(8); _sage_const_2097152 = Integer(2097152); _sage_const_4 = Integer(4)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((lambda_var_0 + (-_sage_const_1  * skoS)) <= -_sage_const_199637 /_sage_const_262144 ), ((-_sage_const_17592181850111 /_sage_const_8796093022208  + (_sage_const_1 /_sage_const_8796093022208  * skoS * (_sage_const_20971521  + (_sage_const_4194304  * skoS * (_sage_const_12582915  + (_sage_const_4194304  * skoS)))))) <= (-_sage_const_1 /_sage_const_549755813888  * (_sage_const_199637  + (_sage_const_262144  * lambda_var_0)) * (-_sage_const_6291457  + (_sage_const_8  * (_sage_const_1  + skoS) * (_sage_const_199637  + (_sage_const_262144  * lambda_var_0))) + (_sage_const_2097152  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


