

# This file was *autogenerated* from the file sage_files/sage_13.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_49909 = Integer(49909); _sage_const_65536 = Integer(65536); _sage_const_274877382655 = Integer(274877382655); _sage_const_137438953472 = Integer(137438953472); _sage_const_2621441 = Integer(2621441); _sage_const_524288 = Integer(524288); _sage_const_1572867 = Integer(1572867); _sage_const_17179869184 = Integer(17179869184); _sage_const_786433 = Integer(786433); _sage_const_4 = Integer(4); _sage_const_262144 = Integer(262144)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((lambda_var_0 + (-_sage_const_1  * skoS)) <= -_sage_const_49909 /_sage_const_65536 ), ((-_sage_const_274877382655 /_sage_const_137438953472  + (_sage_const_1 /_sage_const_137438953472  * skoS * (_sage_const_2621441  + (_sage_const_524288  * skoS * (_sage_const_1572867  + (_sage_const_524288  * skoS)))))) <= (-_sage_const_1 /_sage_const_17179869184  * (_sage_const_49909  + (_sage_const_65536  * lambda_var_0)) * (-_sage_const_786433  + (_sage_const_4  * (_sage_const_1  + skoS) * (_sage_const_49909  + (_sage_const_65536  * lambda_var_0))) + (_sage_const_262144  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


