

# This file was *autogenerated* from the file sage_files/sage_19.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_12776809 = Integer(12776809); _sage_const_16777216 = Integer(16777216); _sage_const_288230375614840831 = Integer(288230375614840831); _sage_const_144115188075855872 = Integer(144115188075855872); _sage_const_2684354561 = Integer(2684354561); _sage_const_536870912 = Integer(536870912); _sage_const_1610612739 = Integer(1610612739); _sage_const_4503599627370496 = Integer(4503599627370496); _sage_const_805306369 = Integer(805306369); _sage_const_16 = Integer(16); _sage_const_268435456 = Integer(268435456); _sage_const_4 = Integer(4)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((lambda_var_0 + (-_sage_const_1  * skoS)) <= -_sage_const_12776809 /_sage_const_16777216 ), ((-_sage_const_288230375614840831 /_sage_const_144115188075855872  + (_sage_const_1 /_sage_const_144115188075855872  * skoS * (_sage_const_2684354561  + (_sage_const_536870912  * skoS * (_sage_const_1610612739  + (_sage_const_536870912  * skoS)))))) <= (-_sage_const_1 /_sage_const_4503599627370496  * (_sage_const_12776809  + (_sage_const_16777216  * lambda_var_0)) * (-_sage_const_805306369  + (_sage_const_16  * (_sage_const_1  + skoS) * (_sage_const_12776809  + (_sage_const_16777216  * lambda_var_0))) + (_sage_const_268435456  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


