

# This file was *autogenerated* from the file sage_files/sage_9.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3119 = Integer(3119); _sage_const_4096 = Integer(4096); _sage_const_17179738111 = Integer(17179738111); _sage_const_8589934592 = Integer(8589934592); _sage_const_655361 = Integer(655361); _sage_const_131072 = Integer(131072); _sage_const_393219 = Integer(393219); _sage_const_268435456 = Integer(268435456); _sage_const_196609 = Integer(196609); _sage_const_16 = Integer(16); _sage_const_65536 = Integer(65536); _sage_const_4 = Integer(4)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((lambda_var_0 + (-_sage_const_1  * skoS)) <= -_sage_const_3119 /_sage_const_4096 ), ((-_sage_const_17179738111 /_sage_const_8589934592  + (_sage_const_1 /_sage_const_8589934592  * skoS * (_sage_const_655361  + (_sage_const_131072  * skoS * (_sage_const_393219  + (_sage_const_131072  * skoS)))))) <= (-_sage_const_1 /_sage_const_268435456  * (_sage_const_3119  + (_sage_const_4096  * lambda_var_0)) * (-_sage_const_196609  + (_sage_const_16  * (_sage_const_1  + skoS) * (_sage_const_3119  + (_sage_const_4096  * lambda_var_0))) + (_sage_const_65536  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


