

# This file was *autogenerated* from the file sage_files/sage_11.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_12477 = Integer(12477); _sage_const_16384 = Integer(16384); _sage_const_68719214591 = Integer(68719214591); _sage_const_34359738368 = Integer(34359738368); _sage_const_1310721 = Integer(1310721); _sage_const_262144 = Integer(262144); _sage_const_786435 = Integer(786435); _sage_const_2147483648 = Integer(2147483648); _sage_const_393217 = Integer(393217); _sage_const_8 = Integer(8); _sage_const_131072 = Integer(131072); _sage_const_4 = Integer(4)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((lambda_var_0 + (-_sage_const_1  * skoS)) <= -_sage_const_12477 /_sage_const_16384 ), ((-_sage_const_68719214591 /_sage_const_34359738368  + (_sage_const_1 /_sage_const_34359738368  * skoS * (_sage_const_1310721  + (_sage_const_262144  * skoS * (_sage_const_786435  + (_sage_const_262144  * skoS)))))) <= (-_sage_const_1 /_sage_const_2147483648  * (_sage_const_12477  + (_sage_const_16384  * lambda_var_0)) * (-_sage_const_393217  + (_sage_const_8  * (_sage_const_1  + skoS) * (_sage_const_12477  + (_sage_const_16384  * lambda_var_0))) + (_sage_const_131072  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


