

# This file was *autogenerated* from the file sage_files/sage_14.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4194304 = Integer(4194304); _sage_const_199637 = Integer(199637); _sage_const_262144 = Integer(262144); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_937168146957 = Integer(937168146957); _sage_const_549755813888 = Integer(549755813888); _sage_const_39854931769 = Integer(39854931769); _sage_const_68719476736 = Integer(68719476736); _sage_const_131072 = Integer(131072); _sage_const_4 = Integer(4); _sage_const_8796093022208 = Integer(8796093022208); _sage_const_20971521 = Integer(20971521); _sage_const_12582915 = Integer(12582915); _sage_const_12582912 = Integer(12582912); _sage_const_4194305 = Integer(4194305)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 >= -_sage_const_1 /_sage_const_4194304 ), (skoS >= _sage_const_199637 /_sage_const_262144 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((_sage_const_937168146957 /_sage_const_549755813888  + (-_sage_const_39854931769 /_sage_const_68719476736  * skoS) + (_sage_const_199637 /_sage_const_131072  * lambda_var_0) + (-_sage_const_199637 /_sage_const_262144  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS))))) >= (-_sage_const_2  + (_sage_const_1 /_sage_const_8796093022208  * skoS * (((_sage_const_1  + (_sage_const_4194304  * lambda_var_0)) * (_sage_const_20971521  + (_sage_const_4194304  * lambda_var_0))) + (_sage_const_4194304  * skoS * (_sage_const_12582915  + (_sage_const_4194304  * skoS) + (_sage_const_12582912  * lambda_var_0))))) + (_sage_const_1 /_sage_const_8796093022208  * (_sage_const_1  + (_sage_const_4194304  * lambda_var_0)) * (_sage_const_4194305  + (_sage_const_4194304  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


