

# This file was *autogenerated* from the file gus_sage_files/sage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_20 = Integer(20); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5)
var('delta')
var('skoX')
var('skoS2')
var('pi')
var('skoSP')
var('skoSM')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS2 >= _sage_const_0 ), (skoSM >= _sage_const_0 ), (skoSP >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (skoX > _sage_const_0 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (skoX < _sage_const_1 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), (delta >= (-_sage_const_1  + skoX + ((skoSM)**_sage_const_2 ))), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1  * ((skoSP)**_sage_const_2 )))), (delta >= (-_sage_const_1  + ((skoSP)**_sage_const_2 ) + (-_sage_const_1  * skoX))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1  * ((skoSM)**_sage_const_2 )))), ((_sage_const_1 /_sage_const_20  * skoSP * (_sage_const_1  + (_sage_const_10  * pi) + (_sage_const_20  * pi * skoS2))) >= (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_20  * skoSM * (-_sage_const_1  + (_sage_const_10  * pi) + (_sage_const_20  * pi * skoS2))))))
E = qf.exists(['skoSM', 'skoSP'],F)
print(qepcad(E, memcells='1000000000 +L5000'))


