

# This file was *autogenerated* from the file sage_files/sage_0.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1)
var('b')
var('delta')
var('a')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (delta >= (-_sage_const_2  + ((b)**_sage_const_3 ))), ((b + (-_sage_const_1  * lambda_var_0)) < _sage_const_2 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((b)**_sage_const_3 )))), (delta >= (-_sage_const_2  + (((_sage_const_2  + lambda_var_0))**_sage_const_2 ))), (delta >= (_sage_const_2  + (-_sage_const_1  * (((_sage_const_2  + lambda_var_0))**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


