

# This file was *autogenerated* from the file gus_sage_files/sage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_9 = Integer(9); _sage_const_20 = Integer(20); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_10 = Integer(10); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_12 = Integer(12)
var('delta')
var('skoS')
var('skoCOSS')
var('skoSINS')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_9 /_sage_const_20 ), (delta >= (-_sage_const_1  + ((skoCOSS)**_sage_const_2 ) + ((skoSINS)**_sage_const_2 ))), (delta >= (_sage_const_1  + (-_sage_const_1  * ((skoCOSS)**_sage_const_2 )) + (-_sage_const_1  * ((skoSINS)**_sage_const_2 )))), ((_sage_const_1 /_sage_const_4  * skoSINS * (_sage_const_10  + (_sage_const_2  * skoCOSS) + (-_sage_const_1  * skoSINS * (_sage_const_1  + skoS)) + (-_sage_const_2  * skoS * (-_sage_const_3  + (skoS * (_sage_const_3  + skoS)))))) >= (_sage_const_2  + (_sage_const_1 /_sage_const_2  * skoCOSS * (_sage_const_6  + skoCOSS)) + (_sage_const_1 /_sage_const_2  * skoS * (_sage_const_12  + (skoCOSS * (_sage_const_12  + skoCOSS)) + (_sage_const_2  * skoS * (_sage_const_6  + (_sage_const_2  * skoS) + (_sage_const_3  * skoCOSS))))))))
E = qf.exists(['skoCOSS', 'skoSINS'],F)
print(qepcad(E, memcells='1000000000 +L5000'))


