

# This file was *autogenerated* from the file sage_files/sage_0.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_53 = Integer(53); _sage_const_40 = Integer(40); _sage_const_63 = Integer(63); _sage_const_20 = Integer(20); _sage_const_80 = Integer(80); _sage_const_65 = Integer(65); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= skoX), (lambda_var_0 > -_sage_const_1 /_sage_const_2 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), (delta >= (-_sage_const_1  * skoX)), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_3 /_sage_const_4  + lambda_var_0 + ((lambda_var_0)**_sage_const_2 ) + (-_sage_const_1  * skoX))), (delta >= (_sage_const_3 /_sage_const_4  + skoX + (-_sage_const_1  * lambda_var_0) + (-_sage_const_1  * ((lambda_var_0)**_sage_const_2 )))), ((_sage_const_53 /_sage_const_40  + (_sage_const_63 /_sage_const_20  * skoS2)) > (_sage_const_1 /_sage_const_80  * (_sage_const_1  + (_sage_const_2  * lambda_var_0)) * (_sage_const_65  + (_sage_const_126  * skoS2)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


