

# This file was *autogenerated* from the file sage_files/sage_13.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_33457 = Integer(33457); _sage_const_32768 = Integer(32768); _sage_const_1 = Integer(1); _sage_const_45577599 = Integer(45577599); _sage_const_1073741824 = Integer(1073741824); _sage_const_2 = Integer(2); _sage_const_416845 = Integer(416845); _sage_const_262144 = Integer(262144); _sage_const_404019 = Integer(404019); _sage_const_131072 = Integer(131072); _sage_const_5 = Integer(5); _sage_const_1310720 = Integer(1310720); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_33457 /_sage_const_32768 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_45577599 /_sage_const_1073741824 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_45577599 /_sage_const_1073741824 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_1073741824  * (((_sage_const_33457  + (_sage_const_32768  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_1073741824  * (((_sage_const_33457  + (_sage_const_32768  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_416845 /_sage_const_262144  + (_sage_const_404019 /_sage_const_131072  * skoS2)) < (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_1310720  * (_sage_const_61  + (_sage_const_126  * skoS2)) * (_sage_const_33457  + (_sage_const_32768  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


