

# This file was *autogenerated* from the file sage_files/sage_14.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_64131 = Integer(64131); _sage_const_65536 = Integer(65536); _sage_const_1 = Integer(1); _sage_const_2916510465 = Integer(2916510465); _sage_const_68719476736 = Integer(68719476736); _sage_const_2 = Integer(2); _sage_const_4294967296 = Integer(4294967296); _sage_const_14229437 = Integer(14229437); _sage_const_10485760 = Integer(10485760); _sage_const_16861887 = Integer(16861887); _sage_const_5242880 = Integer(5242880); _sage_const_2621440 = Integer(2621440); _sage_const_65 = Integer(65); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_64131 /_sage_const_65536 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_2916510465 /_sage_const_68719476736 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_2916510465 /_sage_const_68719476736 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_4294967296  * (((_sage_const_64131  + (_sage_const_65536  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_4294967296  * (((_sage_const_64131  + (_sage_const_65536  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_14229437 /_sage_const_10485760  + (_sage_const_16861887 /_sage_const_5242880  * skoS2)) > (_sage_const_1 /_sage_const_2621440  * (_sage_const_65  + (_sage_const_126  * skoS2)) * (_sage_const_64131  + (_sage_const_65536  * lambda_var_0)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


