

# This file was *autogenerated* from the file sage_files/sage_5.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_67583 = Integer(67583); _sage_const_65536 = Integer(65536); _sage_const_1 = Integer(1); _sage_const_68154303 = Integer(68154303); _sage_const_1073741824 = Integer(1073741824); _sage_const_2 = Integer(2); _sage_const_4294967296 = Integer(4294967296); _sage_const_412243 = Integer(412243); _sage_const_262144 = Integer(262144); _sage_const_1997793 = Integer(1997793); _sage_const_655360 = Integer(655360); _sage_const_5 = Integer(5); _sage_const_2621440 = Integer(2621440); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_67583 /_sage_const_65536 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_68154303 /_sage_const_1073741824 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_68154303 /_sage_const_1073741824 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_4294967296  * (((_sage_const_67583  + (_sage_const_65536  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_4294967296  * (((_sage_const_67583  + (_sage_const_65536  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_412243 /_sage_const_262144  + (_sage_const_1997793 /_sage_const_655360  * skoS2)) < (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_2621440  * (_sage_const_61  + (_sage_const_126  * skoS2)) * (_sage_const_67583  + (_sage_const_65536  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


