

# This file was *autogenerated* from the file sage_files/sage_15.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_267649 = Integer(267649); _sage_const_262144 = Integer(262144); _sage_const_1 = Integer(1); _sage_const_182182135 = Integer(182182135); _sage_const_4294967296 = Integer(4294967296); _sage_const_2 = Integer(2); _sage_const_68719476736 = Integer(68719476736); _sage_const_833703 = Integer(833703); _sage_const_524288 = Integer(524288); _sage_const_4040253 = Integer(4040253); _sage_const_1310720 = Integer(1310720); _sage_const_5 = Integer(5); _sage_const_10485760 = Integer(10485760); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_267649 /_sage_const_262144 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_182182135 /_sage_const_4294967296 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_182182135 /_sage_const_4294967296 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_68719476736  * (((_sage_const_267649  + (_sage_const_262144  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_68719476736  * (((_sage_const_267649  + (_sage_const_262144  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_833703 /_sage_const_524288  + (_sage_const_4040253 /_sage_const_1310720  * skoS2)) < (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_10485760  * (_sage_const_61  + (_sage_const_126  * skoS2)) * (_sage_const_267649  + (_sage_const_262144  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


