

# This file was *autogenerated* from the file sage_files/sage_9.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_523 = Integer(523); _sage_const_512 = Integer(512); _sage_const_1 = Integer(1); _sage_const_759 = Integer(759); _sage_const_16384 = Integer(16384); _sage_const_2 = Integer(2); _sage_const_262144 = Integer(262144); _sage_const_1625 = Integer(1625); _sage_const_1024 = Integer(1024); _sage_const_1575 = Integer(1575); _sage_const_5 = Integer(5); _sage_const_20480 = Integer(20480); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_523 /_sage_const_512 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_759 /_sage_const_16384 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_759 /_sage_const_16384 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_262144  * (((_sage_const_523  + (_sage_const_512  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_262144  * (((_sage_const_523  + (_sage_const_512  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_1625 /_sage_const_1024  + (_sage_const_1575 /_sage_const_512  * skoS2)) < (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_20480  * (_sage_const_61  + (_sage_const_126  * skoS2)) * (_sage_const_523  + (_sage_const_512  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


