

# This file was *autogenerated* from the file sage_files/sage_2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15 = Integer(15); _sage_const_16 = Integer(16); _sage_const_1 = Integer(1); _sage_const_65 = Integer(65); _sage_const_1024 = Integer(1024); _sage_const_2 = Integer(2); _sage_const_256 = Integer(256); _sage_const_1757 = Integer(1757); _sage_const_1280 = Integer(1280); _sage_const_2079 = Integer(2079); _sage_const_640 = Integer(640); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_15 /_sage_const_16 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_65 /_sage_const_1024 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_65 /_sage_const_1024 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_256  * (((_sage_const_15  + (_sage_const_16  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_256  * (((_sage_const_15  + (_sage_const_16  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_1757 /_sage_const_1280  + (_sage_const_2079 /_sage_const_640  * skoS2)) > (_sage_const_1 /_sage_const_640  * (_sage_const_15  + (_sage_const_16  * lambda_var_0)) * (_sage_const_65  + (_sage_const_126  * skoS2)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


