

# This file was *autogenerated* from the file sage_files/sage_11.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_33471 = Integer(33471); _sage_const_32768 = Integer(32768); _sage_const_1 = Integer(1); _sage_const_11143 = Integer(11143); _sage_const_262144 = Integer(262144); _sage_const_2 = Integer(2); _sage_const_1073741824 = Integer(1073741824); _sage_const_6513 = Integer(6513); _sage_const_4096 = Integer(4096); _sage_const_31563 = Integer(31563); _sage_const_10240 = Integer(10240); _sage_const_5 = Integer(5); _sage_const_1310720 = Integer(1310720); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_33471 /_sage_const_32768 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_11143 /_sage_const_262144 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_11143 /_sage_const_262144 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_1073741824  * (((_sage_const_33471  + (_sage_const_32768  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_1073741824  * (((_sage_const_33471  + (_sage_const_32768  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_6513 /_sage_const_4096  + (_sage_const_31563 /_sage_const_10240  * skoS2)) < (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_1310720  * (_sage_const_61  + (_sage_const_126  * skoS2)) * (_sage_const_33471  + (_sage_const_32768  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


