

# This file was *autogenerated* from the file sage_files/sage_10.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_501 = Integer(501); _sage_const_512 = Integer(512); _sage_const_1 = Integer(1); _sage_const_46566017 = Integer(46566017); _sage_const_1073741824 = Integer(1073741824); _sage_const_2 = Integer(2); _sage_const_262144 = Integer(262144); _sage_const_1779587 = Integer(1779587); _sage_const_1310720 = Integer(1310720); _sage_const_2108673 = Integer(2108673); _sage_const_655360 = Integer(655360); _sage_const_20480 = Integer(20480); _sage_const_65 = Integer(65); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_501 /_sage_const_512 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_46566017 /_sage_const_1073741824 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_46566017 /_sage_const_1073741824 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_262144  * (((_sage_const_501  + (_sage_const_512  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_262144  * (((_sage_const_501  + (_sage_const_512  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_1779587 /_sage_const_1310720  + (_sage_const_2108673 /_sage_const_655360  * skoS2)) > (_sage_const_1 /_sage_const_20480  * (_sage_const_65  + (_sage_const_126  * skoS2)) * (_sage_const_501  + (_sage_const_512  * lambda_var_0)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


