

# This file was *autogenerated* from the file gus_sage_files/sage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5)
var('delta')
var('skoS')
var('pi')
var('skoCOSS')
var('skoSINS')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (pi > (_sage_const_2  * skoS)), ((skoSINS * (_sage_const_3  + (_sage_const_2  * skoCOSS) + (-_sage_const_1  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS)))) + (-_sage_const_1  * skoSINS * (_sage_const_1  + skoS)))) < (-_sage_const_2  + (_sage_const_2  * skoCOSS * (_sage_const_1  + skoCOSS)) + (_sage_const_2  * skoS * ((skoCOSS * (_sage_const_5  + skoCOSS)) + (skoS * (_sage_const_3  + skoS + (_sage_const_3  * skoCOSS))))))))
E = qf.exists(['skoSINS', 'skoCOSS'],F)
print(qepcad(E, memcells='1000000000 +L5000'))


