

# This file was *autogenerated* from the file sage_files/sage_1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_63 = Integer(63); _sage_const_64 = Integer(64)
var('delta')
var('skoSINS')
var('skoM')
var('skoCOSS')
var('skoS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (delta >= skoM), (lambda_var_0 >= _sage_const_0 ), (skoM >= _sage_const_2 ), (delta >= (-_sage_const_1  * skoM)), (delta >= (-_sage_const_63 /_sage_const_64  + ((skoSINS)**_sage_const_2 ))), (delta >= (_sage_const_63 /_sage_const_64  + (-_sage_const_1  * ((skoSINS)**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


