

# This file was *autogenerated* from the file gus_sage_files/sage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_217 = Integer(217); _sage_const_100 = Integer(100); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5)
var('delta')
var('skoS')
var('skoCOSS')
var('skoSINS')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_217 /_sage_const_100 ), ((skoSINS * (_sage_const_3  + (_sage_const_2  * skoCOSS) + (-_sage_const_1  * skoS * (-_sage_const_4  + (skoS * (_sage_const_2  + skoS)))) + (-_sage_const_1  * skoSINS * (_sage_const_1  + skoS)))) >= (-_sage_const_2  + (_sage_const_2  * skoCOSS * (_sage_const_1  + skoCOSS)) + (_sage_const_2  * skoS * ((skoCOSS * (_sage_const_5  + skoCOSS)) + (skoS * (_sage_const_3  + skoS + (_sage_const_3  * skoCOSS))))))))
E = qf.exists(['skoCOSS', 'skoSINS'],F)
print(qepcad(E, memcells='1000000000 +L5000'))


