

# This file was *autogenerated* from the file sage_files/sage_1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_9 = Integer(9); _sage_const_20 = Integer(20); _sage_const_143 = Integer(143); _sage_const_17 = Integer(17); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_38 = Integer(38); _sage_const_3 = Integer(3); _sage_const_15 = Integer(15); _sage_const_4 = Integer(4); _sage_const_14 = Integer(14)
var('delta')
var('skoS')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_9 /_sage_const_20 ), (delta >= (_sage_const_143  + (((-_sage_const_17  + lambda_var_0))**_sage_const_2 ))), (delta >= (-_sage_const_143  + (-_sage_const_1  * (((-_sage_const_17  + lambda_var_0))**_sage_const_2 )))), ((_sage_const_38  + (_sage_const_2  * skoS * (_sage_const_3  + (skoS * (-_sage_const_15  + skoS))))) <= (-_sage_const_1 /_sage_const_4  * (-_sage_const_17  + lambda_var_0) * (_sage_const_14  + ((_sage_const_1  + skoS) * (-_sage_const_17  + lambda_var_0)) + (_sage_const_2  * skoS * (-_sage_const_3  + (skoS * (_sage_const_3  + skoS))))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


