

# This file was *autogenerated* from the file sage_files/sage_1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_13 = Integer(13); _sage_const_4 = Integer(4); _sage_const_63 = Integer(63); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_40 = Integer(40); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_1 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((_sage_const_13 /_sage_const_4  + (_sage_const_63 /_sage_const_10  * skoS2)) > (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_40  * (_sage_const_1  + lambda_var_0) * (_sage_const_61  + (_sage_const_126  * skoS2))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


