

# This file was *autogenerated* from the file sage_files/sage_0.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_217 = Integer(217); _sage_const_100 = Integer(100); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_64 = Integer(64); _sage_const_8 = Integer(8); _sage_const_2 = Integer(2)
var('delta')
var('skoS')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_217 /_sage_const_100 ),  qf.or_((delta < (_sage_const_3 /_sage_const_4  + (-_sage_const_1 /_sage_const_64  * (((_sage_const_1  + (_sage_const_8  * lambda_var_0)))**_sage_const_2 )))), (delta < (-_sage_const_3 /_sage_const_4  + (_sage_const_1 /_sage_const_64  * (((_sage_const_1  + (_sage_const_8  * lambda_var_0)))**_sage_const_2 ))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


