

# This file was *autogenerated* from the file sage_files/sage_10.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_181 = Integer(181); _sage_const_128 = Integer(128); _sage_const_1 = Integer(1); _sage_const_255 = Integer(255); _sage_const_256 = Integer(256); _sage_const_2 = Integer(2); _sage_const_16384 = Integer(16384)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_181 /_sage_const_128 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_255 /_sage_const_256 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_255 /_sage_const_256 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_16384  * (((_sage_const_181  + (_sage_const_128  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_16384  * (((_sage_const_181  + (_sage_const_128  * lambda_var_0)))**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


