

# This file was *autogenerated* from the file sage_files/sage_15.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_128 = Integer(128); _sage_const_17178831137 = Integer(17178831137); _sage_const_17179869184 = Integer(17179869184); _sage_const_2 = Integer(2); _sage_const_16383 = Integer(16383); _sage_const_16384 = Integer(16384); _sage_const_64 = Integer(64)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_1 /_sage_const_128 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_17178831137 /_sage_const_17179869184 ), (((skoX)**_sage_const_2 ) > _sage_const_0 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_17178831137 /_sage_const_17179869184 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_16383 /_sage_const_16384  + skoX + ((lambda_var_0)**_sage_const_2 ) + (_sage_const_1 /_sage_const_64  * lambda_var_0))), (delta >= (_sage_const_16383 /_sage_const_16384  + (-_sage_const_1  * skoX) + (-_sage_const_1  * ((lambda_var_0)**_sage_const_2 )) + (-_sage_const_1 /_sage_const_64  * lambda_var_0))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


