

# This file was *autogenerated* from the file sage_files/sage_12.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_11585 = Integer(11585); _sage_const_8192 = Integer(8192); _sage_const_1 = Integer(1); _sage_const_4095 = Integer(4095); _sage_const_4096 = Integer(4096); _sage_const_2 = Integer(2); _sage_const_67108864 = Integer(67108864)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_11585 /_sage_const_8192 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_4095 /_sage_const_4096 ), (((skoX)**_sage_const_2 ) > _sage_const_0 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_4095 /_sage_const_4096 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_67108864  * (((_sage_const_11585  + (_sage_const_8192  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_67108864  * (((_sage_const_11585  + (_sage_const_8192  * lambda_var_0)))**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


