

# This file was *autogenerated* from the file sage_files/sage_6.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_11 = Integer(11); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_15 = Integer(15); _sage_const_16 = Integer(16); _sage_const_2 = Integer(2); _sage_const_64 = Integer(64)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_11 /_sage_const_8 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_15 /_sage_const_16 ), (((skoX)**_sage_const_2 ) > _sage_const_0 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_15 /_sage_const_16 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_64  * (((_sage_const_11  + (_sage_const_8  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_64  * (((_sage_const_11  + (_sage_const_8  * lambda_var_0)))**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


