

# This file was *autogenerated* from the file sage_files/sage_16.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_92681 = Integer(92681); _sage_const_65536 = Integer(65536); _sage_const_1 = Integer(1); _sage_const_65535 = Integer(65535); _sage_const_2 = Integer(2); _sage_const_4294967296 = Integer(4294967296)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_92681 /_sage_const_65536 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_65535 /_sage_const_65536 ), (((skoX)**_sage_const_2 ) > _sage_const_0 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_65535 /_sage_const_65536 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_4294967296  * (((_sage_const_92681  + (_sage_const_65536  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_4294967296  * (((_sage_const_92681  + (_sage_const_65536  * lambda_var_0)))**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


