

# This file was *autogenerated* from the file sage_files/sage_11.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_16 = Integer(16); _sage_const_16377 = Integer(16377); _sage_const_16384 = Integer(16384); _sage_const_2 = Integer(2); _sage_const_255 = Integer(255); _sage_const_256 = Integer(256); _sage_const_8 = Integer(8)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_1 /_sage_const_16 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_16377 /_sage_const_16384 ), (((skoX)**_sage_const_2 ) > _sage_const_0 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_16377 /_sage_const_16384 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_255 /_sage_const_256  + skoX + ((lambda_var_0)**_sage_const_2 ) + (_sage_const_1 /_sage_const_8  * lambda_var_0))), (delta >= (_sage_const_255 /_sage_const_256  + (-_sage_const_1  * skoX) + (-_sage_const_1  * ((lambda_var_0)**_sage_const_2 )) + (-_sage_const_1 /_sage_const_8  * lambda_var_0))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


