

# This file was *autogenerated* from the file sage_files/sage_5.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_23 = Integer(23); _sage_const_32 = Integer(32); _sage_const_1 = Integer(1); _sage_const_9 = Integer(9); _sage_const_16 = Integer(16); _sage_const_2 = Integer(2); _sage_const_1024 = Integer(1024)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_23 /_sage_const_32 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_9 /_sage_const_16 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_9 /_sage_const_16 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_1024  * (((_sage_const_23  + (_sage_const_32  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_1024  * (((_sage_const_23  + (_sage_const_32  * lambda_var_0)))**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


