

# This file was *autogenerated* from the file sage_files/sage_0.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_1 = Integer(1); _sage_const_63 = Integer(63); _sage_const_64 = Integer(64); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4)
var('delta')
var('skoX')
var('pi')
var('skoSP')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (skoX > _sage_const_0 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (skoX < _sage_const_1 ),  qf.or_((delta < (_sage_const_63 /_sage_const_64  + skoX + (-_sage_const_1  * ((lambda_var_0)**_sage_const_2 )) + (-_sage_const_1 /_sage_const_4  * lambda_var_0))), (delta < (-_sage_const_63 /_sage_const_64  + ((lambda_var_0)**_sage_const_2 ) + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_4  * lambda_var_0)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


