

# This file was *autogenerated* from the file sage_files/sage_13.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_339 = Integer(339); _sage_const_512 = Integer(512); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_1 = Integer(1); _sage_const_587265 = Integer(587265); _sage_const_1048576 = Integer(1048576); _sage_const_2 = Integer(2); _sage_const_1024 = Integer(1024); _sage_const_6053 = Integer(6053); _sage_const_262144 = Integer(262144)
var('delta')
var('skoX')
var('skoS2')
var('pi')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 >= -_sage_const_339 /_sage_const_512 ), (skoS2 >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (skoX > _sage_const_0 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_587265 /_sage_const_1048576 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_587265 /_sage_const_1048576 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), ((_sage_const_1 /_sage_const_1024  * skoX * (_sage_const_6053  + (_sage_const_1024  * lambda_var_0))) >= _sage_const_0 ), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_262144  * (((_sage_const_339  + (_sage_const_512  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_262144  * (((_sage_const_339  + (_sage_const_512  * lambda_var_0)))**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


