

# This file was *autogenerated* from the file sage_files/sage_17.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_5419 = Integer(5419); _sage_const_8192 = Integer(8192); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_1 = Integer(1); _sage_const_150953985 = Integer(150953985); _sage_const_268435456 = Integer(268435456); _sage_const_2 = Integer(2); _sage_const_16384 = Integer(16384); _sage_const_96853 = Integer(96853); _sage_const_67108864 = Integer(67108864)
var('delta')
var('skoX')
var('skoS2')
var('pi')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 >= -_sage_const_5419 /_sage_const_8192 ), (skoS2 >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (skoX > _sage_const_0 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_150953985 /_sage_const_268435456 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_150953985 /_sage_const_268435456 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), ((_sage_const_1 /_sage_const_16384  * skoX * (_sage_const_96853  + (_sage_const_16384  * lambda_var_0))) >= _sage_const_0 ), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_67108864  * (((_sage_const_5419  + (_sage_const_8192  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_67108864  * (((_sage_const_5419  + (_sage_const_8192  * lambda_var_0)))**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


