

# This file was *autogenerated* from the file sage_files/sage_15.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1355 = Integer(1355); _sage_const_2048 = Integer(2048); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_1 = Integer(1); _sage_const_9426945 = Integer(9426945); _sage_const_16777216 = Integer(16777216); _sage_const_2 = Integer(2); _sage_const_4096 = Integer(4096); _sage_const_24213 = Integer(24213); _sage_const_4194304 = Integer(4194304)
var('delta')
var('skoX')
var('skoS2')
var('pi')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 >= -_sage_const_1355 /_sage_const_2048 ), (skoS2 >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (skoX > _sage_const_0 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_9426945 /_sage_const_16777216 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_9426945 /_sage_const_16777216 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), ((_sage_const_1 /_sage_const_4096  * skoX * (_sage_const_24213  + (_sage_const_4096  * lambda_var_0))) >= _sage_const_0 ), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_4194304  * (((_sage_const_1355  + (_sage_const_2048  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_4194304  * (((_sage_const_1355  + (_sage_const_2048  * lambda_var_0)))**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


