

# This file was *autogenerated* from the file sage_files/sage_18.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_40959 = Integer(40959); _sage_const_32768 = Integer(32768); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_1 = Integer(1); _sage_const_150994887 = Integer(150994887); _sage_const_268435456 = Integer(268435456); _sage_const_2 = Integer(2); _sage_const_193705 = Integer(193705); _sage_const_1073741824 = Integer(1073741824)
var('delta')
var('skoX')
var('skoS2')
var('pi')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 >= -_sage_const_40959 /_sage_const_32768 ), (skoS2 >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (skoX > _sage_const_0 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_150994887 /_sage_const_268435456 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_150994887 /_sage_const_268435456 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), ((_sage_const_1 /_sage_const_32768  * skoX * (_sage_const_193705  + (_sage_const_32768  * lambda_var_0))) >= _sage_const_0 ), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_1073741824  * (((_sage_const_40959  + (_sage_const_32768  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_1073741824  * (((_sage_const_40959  + (_sage_const_32768  * lambda_var_0)))**_sage_const_2 )))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


