

# This file was *autogenerated* from the file sage_files/sage_1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_9 = Integer(9); _sage_const_20 = Integer(20); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_256 = Integer(256); _sage_const_8 = Integer(8); _sage_const_48 = Integer(48); _sage_const_16 = Integer(16); _sage_const_3 = Integer(3)
var('delta')
var('skoS')
var('skoCOSS')
var('skoSINS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoS >= _sage_const_9 /_sage_const_20 ), ((-_sage_const_2  + (_sage_const_2  * skoS * (-_sage_const_2  + ((skoS)**_sage_const_2 )))) > (-_sage_const_1 /_sage_const_256  * (_sage_const_1  + (_sage_const_8  * lambda_var_0)) * (-_sage_const_48  + ((_sage_const_1  + skoS) * (_sage_const_1  + (_sage_const_8  * lambda_var_0))) + (_sage_const_16  * skoS * (-_sage_const_3  + (skoS * (_sage_const_3  + skoS))))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


