

# This file was *autogenerated* from the file sage_files/sage_8.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_3961 = Integer(3961); _sage_const_4096 = Integer(4096); _sage_const_1 = Integer(1); _sage_const_1090313 = Integer(1090313); _sage_const_16777216 = Integer(16777216); _sage_const_2 = Integer(2); _sage_const_225079 = Integer(225079); _sage_const_163840 = Integer(163840); _sage_const_266301 = Integer(266301); _sage_const_81920 = Integer(81920); _sage_const_65 = Integer(65); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_3961 /_sage_const_4096 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_1090313 /_sage_const_16777216 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_1090313 /_sage_const_16777216 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_16777216  * (((_sage_const_3961  + (_sage_const_4096  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_16777216  * (((_sage_const_3961  + (_sage_const_4096  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_225079 /_sage_const_163840  + (_sage_const_266301 /_sage_const_81920  * skoS2)) >= (_sage_const_1 /_sage_const_163840  * (_sage_const_65  + (_sage_const_126  * skoS2)) * (_sage_const_3961  + (_sage_const_4096  * lambda_var_0)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


