

# This file was *autogenerated* from the file sage_files/sage_13.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_67627 = Integer(67627); _sage_const_65536 = Integer(65536); _sage_const_1 = Integer(1); _sage_const_1113546175 = Integer(1113546175); _sage_const_17179869184 = Integer(17179869184); _sage_const_2 = Integer(2); _sage_const_4294967296 = Integer(4294967296); _sage_const_1647789 = Integer(1647789); _sage_const_1048576 = Integer(1048576); _sage_const_7985439 = Integer(7985439); _sage_const_2621440 = Integer(2621440); _sage_const_5 = Integer(5); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_67627 /_sage_const_65536 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_1113546175 /_sage_const_17179869184 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_1113546175 /_sage_const_17179869184 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_4294967296  * (((_sage_const_67627  + (_sage_const_65536  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_4294967296  * (((_sage_const_67627  + (_sage_const_65536  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_1647789 /_sage_const_1048576  + (_sage_const_7985439 /_sage_const_2621440  * skoS2)) <= (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_2621440  * (_sage_const_61  + (_sage_const_126  * skoS2)) * (_sage_const_67627  + (_sage_const_65536  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


