

# This file was *autogenerated* from the file sage_files/sage_9.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_4227 = Integer(4227); _sage_const_4096 = Integer(4096); _sage_const_1 = Integer(1); _sage_const_1087695 = Integer(1087695); _sage_const_16777216 = Integer(16777216); _sage_const_2 = Integer(2); _sage_const_51493 = Integer(51493); _sage_const_32768 = Integer(32768); _sage_const_249543 = Integer(249543); _sage_const_81920 = Integer(81920); _sage_const_5 = Integer(5); _sage_const_163840 = Integer(163840); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_4227 /_sage_const_4096 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_1087695 /_sage_const_16777216 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_1087695 /_sage_const_16777216 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_16777216  * (((_sage_const_4227  + (_sage_const_4096  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_16777216  * (((_sage_const_4227  + (_sage_const_4096  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_51493 /_sage_const_32768  + (_sage_const_249543 /_sage_const_81920  * skoS2)) <= (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_163840  * (_sage_const_61  + (_sage_const_126  * skoS2)) * (_sage_const_4227  + (_sage_const_4096  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


