

# This file was *autogenerated* from the file sage_files/sage_10.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_63377 = Integer(63377); _sage_const_65536 = Integer(65536); _sage_const_1 = Integer(1); _sage_const_69577145 = Integer(69577145); _sage_const_1073741824 = Integer(1073741824); _sage_const_2 = Integer(2); _sage_const_4294967296 = Integer(4294967296); _sage_const_1800449 = Integer(1800449); _sage_const_1310720 = Integer(1310720); _sage_const_2130219 = Integer(2130219); _sage_const_655360 = Integer(655360); _sage_const_2621440 = Integer(2621440); _sage_const_65 = Integer(65); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_63377 /_sage_const_65536 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_69577145 /_sage_const_1073741824 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_69577145 /_sage_const_1073741824 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_4294967296  * (((_sage_const_63377  + (_sage_const_65536  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_4294967296  * (((_sage_const_63377  + (_sage_const_65536  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_1800449 /_sage_const_1310720  + (_sage_const_2130219 /_sage_const_655360  * skoS2)) >= (_sage_const_1 /_sage_const_2621440  * (_sage_const_65  + (_sage_const_126  * skoS2)) * (_sage_const_63377  + (_sage_const_65536  * lambda_var_0)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


