

# This file was *autogenerated* from the file sage_files/sage_6.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15841 = Integer(15841); _sage_const_16384 = Integer(16384); _sage_const_1 = Integer(1); _sage_const_270465 = Integer(270465); _sage_const_4194304 = Integer(4194304); _sage_const_2 = Integer(2); _sage_const_268435456 = Integer(268435456); _sage_const_112509 = Integer(112509); _sage_const_81920 = Integer(81920); _sage_const_133119 = Integer(133119); _sage_const_40960 = Integer(40960); _sage_const_655360 = Integer(655360); _sage_const_65 = Integer(65); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_15841 /_sage_const_16384 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_270465 /_sage_const_4194304 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_270465 /_sage_const_4194304 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_268435456  * (((_sage_const_15841  + (_sage_const_16384  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_268435456  * (((_sage_const_15841  + (_sage_const_16384  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_112509 /_sage_const_81920  + (_sage_const_133119 /_sage_const_40960  * skoS2)) >= (_sage_const_1 /_sage_const_655360  * (_sage_const_65  + (_sage_const_126  * skoS2)) * (_sage_const_15841  + (_sage_const_16384  * lambda_var_0)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


