

# This file was *autogenerated* from the file sage_files/sage_5.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1057 = Integer(1057); _sage_const_1024 = Integer(1024); _sage_const_1 = Integer(1); _sage_const_17119 = Integer(17119); _sage_const_262144 = Integer(262144); _sage_const_2 = Integer(2); _sage_const_1048576 = Integer(1048576); _sage_const_6435 = Integer(6435); _sage_const_4096 = Integer(4096); _sage_const_6237 = Integer(6237); _sage_const_2048 = Integer(2048); _sage_const_5 = Integer(5); _sage_const_40960 = Integer(40960); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_1057 /_sage_const_1024 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_17119 /_sage_const_262144 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_17119 /_sage_const_262144 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_1048576  * (((_sage_const_1057  + (_sage_const_1024  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_1048576  * (((_sage_const_1057  + (_sage_const_1024  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_6435 /_sage_const_4096  + (_sage_const_6237 /_sage_const_2048  * skoS2)) <= (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_40960  * (_sage_const_61  + (_sage_const_126  * skoS2)) * (_sage_const_1057  + (_sage_const_1024  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


