

# This file was *autogenerated* from the file sage_files/sage_7.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2113 = Integer(2113); _sage_const_2048 = Integer(2048); _sage_const_1 = Integer(1); _sage_const_17498175 = Integer(17498175); _sage_const_268435456 = Integer(268435456); _sage_const_2 = Integer(2); _sage_const_4194304 = Integer(4194304); _sage_const_205933 = Integer(205933); _sage_const_131072 = Integer(131072); _sage_const_997983 = Integer(997983); _sage_const_327680 = Integer(327680); _sage_const_5 = Integer(5); _sage_const_81920 = Integer(81920); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_2113 /_sage_const_2048 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_17498175 /_sage_const_268435456 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_17498175 /_sage_const_268435456 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_4194304  * (((_sage_const_2113  + (_sage_const_2048  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_4194304  * (((_sage_const_2113  + (_sage_const_2048  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_205933 /_sage_const_131072  + (_sage_const_997983 /_sage_const_327680  * skoS2)) <= (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_81920  * (_sage_const_61  + (_sage_const_126  * skoS2)) * (_sage_const_2113  + (_sage_const_2048  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


