

# This file was *autogenerated* from the file sage_files/sage_11.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_33813 = Integer(33813); _sage_const_32768 = Integer(32768); _sage_const_1 = Integer(1); _sage_const_278323167 = Integer(278323167); _sage_const_4294967296 = Integer(4294967296); _sage_const_2 = Integer(2); _sage_const_1073741824 = Integer(1073741824); _sage_const_823901 = Integer(823901); _sage_const_524288 = Integer(524288); _sage_const_3992751 = Integer(3992751); _sage_const_1310720 = Integer(1310720); _sage_const_5 = Integer(5); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_33813 /_sage_const_32768 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_278323167 /_sage_const_4294967296 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_278323167 /_sage_const_4294967296 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_1  + skoX + (_sage_const_1 /_sage_const_1073741824  * (((_sage_const_33813  + (_sage_const_32768  * lambda_var_0)))**_sage_const_2 )))), (delta >= (_sage_const_1  + (-_sage_const_1  * skoX) + (-_sage_const_1 /_sage_const_1073741824  * (((_sage_const_33813  + (_sage_const_32768  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_823901 /_sage_const_524288  + (_sage_const_3992751 /_sage_const_1310720  * skoS2)) <= (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_1310720  * (_sage_const_61  + (_sage_const_126  * skoS2)) * (_sage_const_33813  + (_sage_const_32768  * lambda_var_0))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


