

# This file was *autogenerated* from the file sage_files/sage_14.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_4056065 = Integer(4056065); _sage_const_4194304 = Integer(4194304); _sage_const_1 = Integer(1); _sage_const_285130813121 = Integer(285130813121); _sage_const_4398046511104 = Integer(4398046511104); _sage_const_2 = Integer(2); _sage_const_17592186044416 = Integer(17592186044416); _sage_const_115230749 = Integer(115230749); _sage_const_83886080 = Integer(83886080); _sage_const_27267219 = Integer(27267219); _sage_const_8388608 = Integer(8388608); _sage_const_167772160 = Integer(167772160); _sage_const_65 = Integer(65); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_4056065 /_sage_const_4194304 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_285130813121 /_sage_const_4398046511104 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_285130813121 /_sage_const_4398046511104 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_17592186044416  * (((_sage_const_4056065  + (_sage_const_4194304  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_17592186044416  * (((_sage_const_4056065  + (_sage_const_4194304  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_115230749 /_sage_const_83886080  + (_sage_const_27267219 /_sage_const_8388608  * skoS2)) >= (_sage_const_1 /_sage_const_167772160  * (_sage_const_65  + (_sage_const_126  * skoS2)) * (_sage_const_4056065  + (_sage_const_4194304  * lambda_var_0)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


