

# This file was *autogenerated* from the file sage_files/sage_12.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_126753 = Integer(126753); _sage_const_131072 = Integer(131072); _sage_const_1 = Integer(1); _sage_const_278443833 = Integer(278443833); _sage_const_4294967296 = Integer(4294967296); _sage_const_2 = Integer(2); _sage_const_17179869184 = Integer(17179869184); _sage_const_3600959 = Integer(3600959); _sage_const_2621440 = Integer(2621440); _sage_const_4260501 = Integer(4260501); _sage_const_1310720 = Integer(1310720); _sage_const_5242880 = Integer(5242880); _sage_const_65 = Integer(65); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_126753 /_sage_const_131072 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= -_sage_const_278443833 /_sage_const_4294967296 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= _sage_const_278443833 /_sage_const_4294967296 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_17179869184  * (((_sage_const_126753  + (_sage_const_131072  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_17179869184  * (((_sage_const_126753  + (_sage_const_131072  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_3600959 /_sage_const_2621440  + (_sage_const_4260501 /_sage_const_1310720  * skoS2)) >= (_sage_const_1 /_sage_const_5242880  * (_sage_const_65  + (_sage_const_126  * skoS2)) * (_sage_const_126753  + (_sage_const_131072  * lambda_var_0)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


