

# This file was *autogenerated* from the file sage_files/sage_0.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_22 = Integer(22); _sage_const_3 = Integer(3); _sage_const_20 = Integer(20); _sage_const_8 = Integer(8); _sage_const_484 = Integer(484); _sage_const_16 = Integer(16); _sage_const_44 = Integer(44); _sage_const_264 = Integer(264); _sage_const_12 = Integer(12)
var('delta')
var('skoSINS')
var('skoM')
var('skoCOSS')
var('skoS')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (skoM >= _sage_const_2 ), (((skoM)**_sage_const_2 ) > _sage_const_0 ), (delta >= (-_sage_const_1  + ((skoSINS)**_sage_const_2 ) + (((-_sage_const_22  + lambda_var_0))**_sage_const_2 ))), (delta >= (_sage_const_1  + (-_sage_const_1  * ((skoSINS)**_sage_const_2 )) + (-_sage_const_1  * (((-_sage_const_22  + lambda_var_0))**_sage_const_2 )))), ((_sage_const_2  * skoSINS * ((skoM)**_sage_const_3 ) * (_sage_const_22  + (-_sage_const_1  * lambda_var_0) + (_sage_const_2  * skoSINS) + (_sage_const_20  * skoM))) <= (_sage_const_8  * ((skoM)**_sage_const_3 ) * (-_sage_const_484  + (-_sage_const_1  * ((lambda_var_0)**_sage_const_2 )) + (-_sage_const_16  * ((skoM)**_sage_const_2 )) + (_sage_const_44  * lambda_var_0) + (_sage_const_264  * skoM) + (-_sage_const_12  * lambda_var_0 * skoM)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


