

# This file was *autogenerated* from the file sage_files/sage_17.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_256 = Integer(256); _sage_const_1073746457 = Integer(1073746457); _sage_const_1073741824 = Integer(1073741824); _sage_const_2 = Integer(2); _sage_const_65535 = Integer(65535); _sage_const_65536 = Integer(65536); _sage_const_128 = Integer(128); _sage_const_602433 = Integer(602433); _sage_const_262144 = Integer(262144); _sage_const_2919483 = Integer(2919483); _sage_const_655360 = Integer(655360); _sage_const_5 = Integer(5); _sage_const_10240 = Integer(10240); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_1 /_sage_const_256 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_1073746457 /_sage_const_1073741824 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_1073746457 /_sage_const_1073741824 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_65535 /_sage_const_65536  + skoX + ((lambda_var_0)**_sage_const_2 ) + (_sage_const_1 /_sage_const_128  * lambda_var_0))), (delta >= (_sage_const_65535 /_sage_const_65536  + (-_sage_const_1  * skoX) + (-_sage_const_1  * ((lambda_var_0)**_sage_const_2 )) + (-_sage_const_1 /_sage_const_128  * lambda_var_0))), ((_sage_const_602433 /_sage_const_262144  + (_sage_const_2919483 /_sage_const_655360  * skoS2)) >= (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_10240  * (_sage_const_1  + (_sage_const_256  * lambda_var_0)) * (_sage_const_61  + (_sage_const_126  * skoS2))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


