

# This file was *autogenerated* from the file sage_files/sage_6.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_11 = Integer(11); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_15 = Integer(15); _sage_const_16 = Integer(16); _sage_const_2 = Integer(2); _sage_const_64 = Integer(64); _sage_const_29 = Integer(29); _sage_const_160 = Integer(160); _sage_const_63 = Integer(63); _sage_const_80 = Integer(80); _sage_const_320 = Integer(320); _sage_const_65 = Integer(65); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_11 /_sage_const_8 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_15 /_sage_const_16 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_15 /_sage_const_16 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_64  * (((_sage_const_11  + (_sage_const_8  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_64  * (((_sage_const_11  + (_sage_const_8  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_29 /_sage_const_160  + (_sage_const_63 /_sage_const_80  * skoS2)) <= (_sage_const_1 /_sage_const_320  * (_sage_const_11  + (_sage_const_8  * lambda_var_0)) * (_sage_const_65  + (_sage_const_126  * skoS2)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


