

# This file was *autogenerated* from the file sage_files/sage_16.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_46341 = Integer(46341); _sage_const_32768 = Integer(32768); _sage_const_1 = Integer(1); _sage_const_65535 = Integer(65535); _sage_const_65536 = Integer(65536); _sage_const_2 = Integer(2); _sage_const_1073741824 = Integer(1073741824); _sage_const_1987 = Integer(1987); _sage_const_10240 = Integer(10240); _sage_const_63 = Integer(63); _sage_const_5120 = Integer(5120); _sage_const_1310720 = Integer(1310720); _sage_const_65 = Integer(65); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_46341 /_sage_const_32768 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_65535 /_sage_const_65536 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_65535 /_sage_const_65536 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_1073741824  * (((_sage_const_46341  + (_sage_const_32768  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_1073741824  * (((_sage_const_46341  + (_sage_const_32768  * lambda_var_0)))**_sage_const_2 )))), ((-_sage_const_1987 /_sage_const_10240  + (_sage_const_63 /_sage_const_5120  * skoS2)) <= (_sage_const_1 /_sage_const_1310720  * (_sage_const_65  + (_sage_const_126  * skoS2)) * (_sage_const_46341  + (_sage_const_32768  * lambda_var_0)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


