

# This file was *autogenerated* from the file sage_files/sage_13.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_64 = Integer(64); _sage_const_16781633 = Integer(16781633); _sage_const_16777216 = Integer(16777216); _sage_const_2 = Integer(2); _sage_const_4095 = Integer(4095); _sage_const_4096 = Integer(4096); _sage_const_32 = Integer(32); _sage_const_75309 = Integer(75309); _sage_const_32768 = Integer(32768); _sage_const_364959 = Integer(364959); _sage_const_81920 = Integer(81920); _sage_const_5 = Integer(5); _sage_const_2560 = Integer(2560); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_1 /_sage_const_64 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_16781633 /_sage_const_16777216 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_16781633 /_sage_const_16777216 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_4095 /_sage_const_4096  + skoX + ((lambda_var_0)**_sage_const_2 ) + (_sage_const_1 /_sage_const_32  * lambda_var_0))), (delta >= (_sage_const_4095 /_sage_const_4096  + (-_sage_const_1  * skoX) + (-_sage_const_1  * ((lambda_var_0)**_sage_const_2 )) + (-_sage_const_1 /_sage_const_32  * lambda_var_0))), ((_sage_const_75309 /_sage_const_32768  + (_sage_const_364959 /_sage_const_81920  * skoS2)) >= (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_2560  * (_sage_const_1  + (_sage_const_64  * lambda_var_0)) * (_sage_const_61  + (_sage_const_126  * skoS2))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


