

# This file was *autogenerated* from the file sage_files/sage_10.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_181 = Integer(181); _sage_const_128 = Integer(128); _sage_const_1 = Integer(1); _sage_const_255 = Integer(255); _sage_const_256 = Integer(256); _sage_const_2 = Integer(2); _sage_const_16384 = Integer(16384); _sage_const_67 = Integer(67); _sage_const_640 = Integer(640); _sage_const_63 = Integer(63); _sage_const_320 = Integer(320); _sage_const_5120 = Integer(5120); _sage_const_65 = Integer(65); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_181 /_sage_const_128 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_255 /_sage_const_256 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_255 /_sage_const_256 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_16384  * (((_sage_const_181  + (_sage_const_128  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_16384  * (((_sage_const_181  + (_sage_const_128  * lambda_var_0)))**_sage_const_2 )))), ((-_sage_const_67 /_sage_const_640  + (_sage_const_63 /_sage_const_320  * skoS2)) <= (_sage_const_1 /_sage_const_5120  * (_sage_const_65  + (_sage_const_126  * skoS2)) * (_sage_const_181  + (_sage_const_128  * lambda_var_0)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


