

# This file was *autogenerated* from the file sage_files/sage_7.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_57 = Integer(57); _sage_const_64 = Integer(64); _sage_const_2 = Integer(2); _sage_const_15 = Integer(15); _sage_const_16 = Integer(16); _sage_const_143 = Integer(143); _sage_const_693 = Integer(693); _sage_const_160 = Integer(160); _sage_const_5 = Integer(5); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_1 /_sage_const_4 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_57 /_sage_const_64 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_57 /_sage_const_64 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_15 /_sage_const_16  + skoX + ((lambda_var_0)**_sage_const_2 ) + (_sage_const_1 /_sage_const_2  * lambda_var_0))), (delta >= (_sage_const_15 /_sage_const_16  + (-_sage_const_1  * skoX) + (-_sage_const_1  * ((lambda_var_0)**_sage_const_2 )) + (-_sage_const_1 /_sage_const_2  * lambda_var_0))), ((_sage_const_143 /_sage_const_64  + (_sage_const_693 /_sage_const_160  * skoS2)) >= (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_160  * (_sage_const_1  + (_sage_const_4  * lambda_var_0)) * (_sage_const_61  + (_sage_const_126  * skoS2))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


