

# This file was *autogenerated* from the file sage_files/sage_4.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_7 = Integer(7); _sage_const_16 = Integer(16); _sage_const_2 = Integer(2); _sage_const_151 = Integer(151); _sage_const_160 = Integer(160); _sage_const_189 = Integer(189); _sage_const_80 = Integer(80); _sage_const_65 = Integer(65); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_5 /_sage_const_4 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_7 /_sage_const_16 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_7 /_sage_const_16 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (_sage_const_1  + skoX + (-_sage_const_1 /_sage_const_16  * (((_sage_const_5  + (_sage_const_4  * lambda_var_0)))**_sage_const_2 )))), (delta >= (-_sage_const_1  + (-_sage_const_1  * skoX) + (_sage_const_1 /_sage_const_16  * (((_sage_const_5  + (_sage_const_4  * lambda_var_0)))**_sage_const_2 )))), ((_sage_const_151 /_sage_const_160  + (_sage_const_189 /_sage_const_80  * skoS2)) <= (_sage_const_1 /_sage_const_160  * (_sage_const_5  + (_sage_const_4  * lambda_var_0)) * (_sage_const_65  + (_sage_const_126  * skoS2)))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


