

# This file was *autogenerated* from the file sage_files/sage_9.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_1001 = Integer(1001); _sage_const_1024 = Integer(1024); _sage_const_2 = Integer(2); _sage_const_63 = Integer(63); _sage_const_64 = Integer(64); _sage_const_4 = Integer(4); _sage_const_585 = Integer(585); _sage_const_256 = Integer(256); _sage_const_567 = Integer(567); _sage_const_128 = Integer(128); _sage_const_5 = Integer(5); _sage_const_320 = Integer(320); _sage_const_61 = Integer(61); _sage_const_126 = Integer(126)
var('delta')
var('skoX')
var('skoS2')
var('skoSP')
var('skoSM')
var('lambda_var_0')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (lambda_var_0 > -_sage_const_1 /_sage_const_8 ), (skoS2 > _sage_const_0 ), (skoX > _sage_const_0 ), (skoX < _sage_const_1 ), ((delta + skoX) >= _sage_const_1001 /_sage_const_1024 ), (delta >= (-_sage_const_2  + ((skoS2)**_sage_const_2 ))), ((delta + (-_sage_const_1  * skoX)) >= -_sage_const_1001 /_sage_const_1024 ), (delta >= (_sage_const_2  + (-_sage_const_1  * ((skoS2)**_sage_const_2 )))), (delta >= (-_sage_const_63 /_sage_const_64  + skoX + ((lambda_var_0)**_sage_const_2 ) + (_sage_const_1 /_sage_const_4  * lambda_var_0))), (delta >= (_sage_const_63 /_sage_const_64  + (-_sage_const_1  * skoX) + (-_sage_const_1  * ((lambda_var_0)**_sage_const_2 )) + (-_sage_const_1 /_sage_const_4  * lambda_var_0))), ((_sage_const_585 /_sage_const_256  + (_sage_const_567 /_sage_const_128  * skoS2)) >= (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_320  * (_sage_const_1  + (_sage_const_8  * lambda_var_0)) * (_sage_const_61  + (_sage_const_126  * skoS2))))))
E = qf.exists([lambda_var_0],F)
print(qepcad(E, memcells='1000000000 +L5000'))


