

# This file was *autogenerated* from the file gus_sage_files/sage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_15707963 = Integer(15707963); _sage_const_5000000 = Integer(5000000); _sage_const_31415927 = Integer(31415927); _sage_const_10000000 = Integer(10000000); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_20 = Integer(20); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5)
var('delta')
var('skoX')
var('skoS2')
var('pi')
var('skoSP')
var('skoSM')
qf = qepcad_formula
F = qf.and_((delta >= _sage_const_0 ), (pi > _sage_const_15707963 /_sage_const_5000000 ), (skoX > _sage_const_0 ), (pi < _sage_const_31415927 /_sage_const_10000000 ), (skoX < _sage_const_1 ), ((skoX * (_sage_const_4  + skoSM + skoSP)) < _sage_const_0 ), ((_sage_const_1 /_sage_const_20  * skoSP * (_sage_const_1  + (_sage_const_10  * pi) + (_sage_const_20  * pi * skoS2))) < (-_sage_const_1 /_sage_const_5  + (_sage_const_1 /_sage_const_20  * skoSM * (-_sage_const_1  + (_sage_const_10  * pi) + (_sage_const_20  * pi * skoS2))))))
E = qf.exists(['skoSM', 'skoSP'],F)
print(qepcad(E, memcells='1000000000 +L5000'))


